const ROUTE_ROOT = '/';
const ROUTE_MAJOR_ADD_INFO = '/add';
const ROUTE_MAJOR_LIST_INFO = '/list';

const ROUTE_MINOR_CUSTOMER = 'customer';
const ROUTE_MINOR_FIELD = 'field';

export {
  ROUTE_ROOT,
  ROUTE_MAJOR_ADD_INFO,
  ROUTE_MAJOR_LIST_INFO,
  ROUTE_MINOR_CUSTOMER,
  ROUTE_MINOR_FIELD,
};
